-- DML: Respondents Seed Data (80 Murid + 20 Staff = 100 Total)
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A1', 'Anisa Aditya', 'anisa.aditya75@yahoo.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A2', 'Dewi Lestari', 'dewi.lestari91@yahoo.com', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A3', 'Rina Mulyani', 'rina.mulyani33@outlook.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A4', 'Sri Wulandari', 'sri.wulandari41@gmail.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A5', 'Hendra Wijaya', 'hendra.wijaya75@outlook.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A6', 'Ayu Saputro', 'ayu.saputro27@gmail.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A7', 'Lestari Rahma', 'lestari.rahma54@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A8', 'Muhammad Kusuma', 'muhammad.kusuma70@gmail.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A9', 'Hendra Mulyani', 'hendra.mulyani41@gmail.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A10', 'Fitri Puspitasari', 'fitri.puspitasari63@gmail.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A11', 'Indah Wijaya', 'indah.wijaya35@outlook.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A12', 'Sri Mulyani', 'sri.mulyani33@outlook.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A13', 'Lestari Puspitasari', 'lestari.puspitasari23@gmail.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A14', 'Andi Kusumawati', 'andi.kusumawati24@gmail.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A15', 'Ratna Santoso', 'ratna.santoso97@gmail.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A16', 'Dwi Rahma', 'dwi.rahma76@outlook.co.id', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A17', 'Bambang Maulana', 'bambang.maulana53@gmail.com', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A18', 'Joko Prabowo', 'joko.prabowo81@gmail.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A19', 'Rina Astuti', 'rina.astuti16@gmail.co.id', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A20', 'Putri Wijaya', 'putri.wijaya33@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A21', 'Dimas Handayani', 'dimas.handayani66@outlook.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A22', 'Fitri Sari', 'fitri.sari72@gmail.com', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A23', 'Bambang Lestari', 'bambang.lestari78@outlook.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A24', 'Lestari Astuti', 'lestari.astuti26@outlook.co.id', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A25', 'Joko Maulana', 'joko.maulana54@yahoo.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A26', 'Fajar Prabowo', 'fajar.prabowo37@gmail.co.id', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A27', 'Reza Wahyuni', 'reza.wahyuni48@gmail.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A28', 'Yuni Nurhaliza', 'yuni.nurhaliza27@yahoo.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A29', 'Fajar Lestari', 'fajar.lestari14@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A30', 'Wahyu Sari', 'wahyu.sari66@outlook.co.id', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A31', 'Rizky Kusuma', 'rizky.kusuma30@gmail.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A32', 'Rahma Wulandari', 'rahma.wulandari28@outlook.co.id', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A33', 'Lestari Kusuma', 'lestari.kusuma57@gmail.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A34', 'Rina Saputra', 'rina.saputra54@outlook.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A35', 'Arif Setiawan', 'arif.setiawan17@gmail.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A36', 'Nur Setiawan', 'nur.setiawan11@gmail.com', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A37', 'Indah Saputro', 'indah.saputro17@outlook.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A38', 'Putri Maulana', 'putri.maulana97@yahoo.com', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A39', 'Sari Saputro', 'sari.saputro64@outlook.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A40', 'Tri Saputra', 'tri.saputra77@outlook.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A41', 'Ahmad Setiawan', 'ahmad.setiawan11@gmail.co.id', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A42', 'Fajar Pertiwi', 'fajar.pertiwi80@gmail.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A43', 'Ayu Aditya', 'ayu.aditya90@outlook.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A44', 'Rudi Anggraini', 'rudi.anggraini35@yahoo.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A45', 'Reza Saputra', 'reza.saputra43@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A46', 'Dimas Lestari', 'dimas.lestari95@outlook.co.id', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A47', 'Budi Pratama', 'budi.pratama83@yahoo.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A48', 'Anisa Nugroho', 'anisa.nugroho21@yahoo.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A49', 'Tri Astuti', 'tri.astuti58@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A50', 'Ratna Wahyuni', 'ratna.wahyuni90@gmail.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A51', 'Agus Anggraini', 'agus.anggraini30@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A52', 'Tri Lestari', 'tri.lestari89@gmail.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A53', 'Dewi Wulandari', 'dewi.wulandari26@gmail.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A54', 'Andi Saputro', 'andi.saputro59@yahoo.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A55', 'Putri Utami', 'putri.utami38@gmail.co.id', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A56', 'Sri Astuti', 'sri.astuti84@outlook.co.id', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A57', 'Anisa Rahma', 'anisa.rahma31@yahoo.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A58', 'Agus Santoso', 'agus.santoso12@yahoo.com', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A59', 'Hendra Utami', 'hendra.utami19@outlook.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A60', 'Anisa Santoso', 'anisa.santoso84@gmail.co.id', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A61', 'Agus Firmansyah', 'agus.firmansyah60@yahoo.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A62', 'Yuni Kurniawan', 'yuni.kurniawan68@gmail.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A63', 'Fitri Nurhaliza', 'fitri.nurhaliza57@outlook.co.id', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A64', 'Dwi Wulandari', 'dwi.wulandari45@gmail.com', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A65', 'Putri Hidayat', 'putri.hidayat97@yahoo.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A66', 'Siti Fauzi', 'siti.fauzi75@outlook.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A67', 'Indah Anggraini', 'indah.anggraini37@outlook.co.id', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A68', 'Rudi Nugroho', 'rudi.nugroho47@gmail.co.id', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A69', 'Arif Maulana', 'arif.maulana46@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A70', 'Rahma Lestari', 'rahma.lestari73@gmail.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A71', 'Bambang Sari', 'bambang.sari26@gmail.co.id', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A72', 'Iwan Saputro', 'iwan.saputro96@yahoo.com', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A73', 'Lestari Setiawan', 'lestari.setiawan54@gmail.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A74', 'Yuni Saputro', 'yuni.saputro51@gmail.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A75', 'Tri Hidayat', 'tri.hidayat24@gmail.co.id', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A76', 'Muhammad Aditya', 'muhammad.aditya18@gmail.com', 'SMP IBG', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A77', 'Rahma Santoso', 'rahma.santoso30@gmail.com', 'SMK 1 Ciomas', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A78', 'Tri Wahyuni', 'tri.wahyuni36@yahoo.com', 'SMAN 4 Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A79', 'Endang Handayani', 'endang.handayani48@gmail.co.id', 'SMP Informatika Bina Generasi', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A80', 'Dian Pratama', 'dian.pratama47@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Murid');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A81', 'Bpk. Muhammad Nugroho', 'muhammad.nugroho49@gmail.co.id', 'SMP Informatika Bina Generasi', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A82', 'Ir. Indah Kusuma', 'indah.kusuma28@gmail.co.id', 'SMAN 4 Bogor', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A83', 'Ir. Muhammad Wijaya', 'muhammad.wijaya24@outlook.co.id', 'SMK 1 Ciomas', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A84', 'S.Pd. Muhammad Firmansyah', 'muhammad.firmansyah97@outlook.co.id', 'SMAN 4 Bogor', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A85', 'Prof. Arif Anggraini', 'arif.anggraini84@yahoo.com', 'SMP IBG', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A86', 'Bpk. Muhammad Anggraini', 'muhammad.anggraini16@gmail.com', 'SMP Informatika Bina Generasi', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A87', 'M.Pd. Indah Firmansyah', 'indah.firmansyah68@gmail.com', 'SMK 1 Ciomas', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A88', 'S.Pd. Tuti Santoso', 'tuti.santoso40@yahoo.com', 'SMP Informatika Bina Generasi', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A89', 'Ibu Siti Maulana', 'siti.maulana15@gmail.com', 'SMAN 4 Bogor', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A90', 'Ir. Eko Hidayat', 'eko.hidayat78@gmail.co.id', 'SMP Informatika Bina Generasi', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A91', 'Ir. Fitri Fauzi', 'fitri.fauzi33@outlook.co.id', 'SMAN 4 Bogor', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A92', 'Ibu Ahmad Susilo', 'ahmad.susilo91@gmail.com', 'SMAN 4 Bogor', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A93', 'Dra. Ilham Nurhaliza', 'ilham.nurhaliza70@gmail.com', 'SMP IBG', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A94', 'S.Pd. Lestari Maulana', 'lestari.maulana45@gmail.com', 'SMP Informatika Bina Generasi', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A95', 'Bpk. Endang Wahyuni', 'endang.wahyuni19@gmail.com', 'SMP Informatika Bina Generasi', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A96', 'Ir. Tri Wijaya', 'tri.wijaya98@gmail.com', 'SMP Informatika Bina Generasi', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A97', 'Ir. Indah Kurniawan', 'indah.kurniawan91@outlook.co.id', 'SMAN 4 Bogor', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A98', 'S.Pd. Siti Susilo', 'siti.susilo65@yahoo.com', 'SMP Informatika Bina Generasi', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A99', 'Ibu Dwi Wulandari', 'dwi.wulandari90@yahoo.com', 'SMA Negeri 4 Kota Bogor', 'Staff');
INSERT INTO respondents (id, name, email, school, consumer_type) VALUES ('A100', 'Dra. Rizky Handayani', 'rizky.handayani29@outlook.co.id', 'SMP Informatika Bina Generasi', 'Staff');

-- DML: Evaluations Seed Data (Normalized: respondent_id, criteria_id, value)
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A1', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A1', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A1', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A1', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A1', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A1', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A1', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A1', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A2', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A2', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A2', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A2', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A2', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A2', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A2', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A2', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A3', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A3', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A3', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A3', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A3', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A3', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A3', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A3', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A4', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A4', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A4', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A4', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A4', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A4', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A4', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A4', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A5', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A5', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A5', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A5', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A5', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A5', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A5', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A5', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A6', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A6', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A6', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A6', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A6', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A6', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A6', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A6', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A7', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A7', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A7', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A7', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A7', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A7', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A7', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A7', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A8', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A8', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A8', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A8', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A8', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A8', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A8', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A8', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A9', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A9', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A9', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A9', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A9', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A9', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A9', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A9', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A10', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A10', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A10', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A10', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A10', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A10', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A10', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A10', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A11', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A11', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A11', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A11', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A11', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A11', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A11', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A11', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A12', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A12', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A12', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A12', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A12', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A12', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A12', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A12', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A13', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A13', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A13', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A13', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A13', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A13', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A13', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A13', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A14', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A14', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A14', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A14', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A14', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A14', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A14', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A14', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A15', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A15', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A15', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A15', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A15', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A15', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A15', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A15', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A16', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A16', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A16', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A16', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A16', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A16', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A16', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A16', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A17', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A17', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A17', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A17', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A17', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A17', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A17', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A17', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A18', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A18', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A18', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A18', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A18', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A18', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A18', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A18', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A19', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A19', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A19', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A19', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A19', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A19', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A19', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A19', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A20', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A20', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A20', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A20', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A20', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A20', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A20', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A20', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A21', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A21', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A21', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A21', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A21', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A21', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A21', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A21', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A22', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A22', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A22', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A22', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A22', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A22', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A22', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A22', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A23', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A23', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A23', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A23', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A23', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A23', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A23', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A23', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A24', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A24', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A24', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A24', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A24', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A24', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A24', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A24', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A25', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A25', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A25', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A25', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A25', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A25', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A25', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A25', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A26', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A26', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A26', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A26', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A26', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A26', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A26', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A26', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A27', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A27', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A27', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A27', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A27', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A27', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A27', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A27', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A28', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A28', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A28', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A28', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A28', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A28', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A28', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A28', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A29', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A29', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A29', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A29', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A29', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A29', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A29', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A29', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A30', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A30', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A30', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A30', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A30', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A30', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A30', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A30', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A31', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A31', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A31', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A31', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A31', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A31', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A31', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A31', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A32', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A32', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A32', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A32', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A32', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A32', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A32', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A32', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A33', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A33', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A33', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A33', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A33', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A33', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A33', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A33', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A34', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A34', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A34', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A34', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A34', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A34', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A34', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A34', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A35', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A35', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A35', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A35', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A35', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A35', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A35', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A35', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A36', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A36', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A36', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A36', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A36', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A36', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A36', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A36', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A37', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A37', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A37', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A37', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A37', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A37', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A37', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A37', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A38', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A38', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A38', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A38', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A38', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A38', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A38', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A38', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A39', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A39', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A39', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A39', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A39', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A39', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A39', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A39', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A40', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A40', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A40', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A40', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A40', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A40', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A40', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A40', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A41', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A41', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A41', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A41', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A41', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A41', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A41', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A41', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A42', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A42', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A42', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A42', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A42', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A42', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A42', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A42', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A43', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A43', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A43', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A43', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A43', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A43', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A43', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A43', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A44', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A44', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A44', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A44', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A44', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A44', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A44', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A44', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A45', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A45', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A45', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A45', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A45', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A45', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A45', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A45', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A46', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A46', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A46', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A46', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A46', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A46', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A46', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A46', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A47', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A47', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A47', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A47', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A47', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A47', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A47', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A47', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A48', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A48', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A48', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A48', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A48', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A48', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A48', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A48', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A49', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A49', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A49', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A49', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A49', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A49', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A49', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A49', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A50', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A50', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A50', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A50', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A50', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A50', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A50', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A50', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A51', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A51', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A51', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A51', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A51', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A51', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A51', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A51', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A52', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A52', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A52', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A52', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A52', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A52', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A52', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A52', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A53', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A53', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A53', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A53', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A53', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A53', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A53', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A53', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A54', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A54', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A54', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A54', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A54', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A54', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A54', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A54', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A55', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A55', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A55', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A55', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A55', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A55', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A55', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A55', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A56', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A56', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A56', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A56', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A56', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A56', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A56', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A56', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A57', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A57', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A57', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A57', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A57', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A57', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A57', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A57', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A58', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A58', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A58', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A58', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A58', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A58', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A58', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A58', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A59', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A59', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A59', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A59', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A59', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A59', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A59', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A59', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A60', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A60', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A60', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A60', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A60', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A60', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A60', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A60', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A61', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A61', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A61', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A61', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A61', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A61', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A61', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A61', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A62', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A62', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A62', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A62', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A62', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A62', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A62', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A62', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A63', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A63', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A63', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A63', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A63', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A63', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A63', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A63', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A64', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A64', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A64', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A64', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A64', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A64', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A64', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A64', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A65', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A65', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A65', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A65', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A65', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A65', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A65', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A65', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A66', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A66', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A66', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A66', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A66', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A66', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A66', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A66', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A67', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A67', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A67', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A67', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A67', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A67', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A67', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A67', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A68', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A68', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A68', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A68', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A68', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A68', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A68', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A68', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A69', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A69', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A69', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A69', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A69', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A69', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A69', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A69', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A70', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A70', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A70', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A70', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A70', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A70', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A70', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A70', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A71', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A71', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A71', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A71', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A71', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A71', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A71', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A71', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A72', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A72', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A72', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A72', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A72', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A72', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A72', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A72', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A73', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A73', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A73', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A73', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A73', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A73', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A73', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A73', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A74', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A74', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A74', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A74', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A74', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A74', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A74', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A74', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A75', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A75', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A75', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A75', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A75', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A75', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A75', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A75', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A76', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A76', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A76', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A76', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A76', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A76', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A76', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A76', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A77', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A77', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A77', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A77', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A77', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A77', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A77', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A77', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A78', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A78', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A78', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A78', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A78', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A78', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A78', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A78', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A79', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A79', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A79', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A79', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A79', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A79', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A79', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A79', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A80', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A80', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A80', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A80', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A80', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A80', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A80', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A80', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A81', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A81', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A81', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A81', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A81', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A81', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A81', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A81', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A82', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A82', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A82', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A82', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A82', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A82', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A82', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A82', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A83', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A83', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A83', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A83', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A83', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A83', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A83', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A83', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A84', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A84', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A84', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A84', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A84', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A84', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A84', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A84', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A85', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A85', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A85', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A85', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A85', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A85', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A85', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A85', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A86', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A86', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A86', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A86', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A86', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A86', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A86', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A86', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A87', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A87', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A87', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A87', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A87', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A87', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A87', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A87', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A88', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A88', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A88', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A88', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A88', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A88', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A88', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A88', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A89', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A89', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A89', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A89', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A89', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A89', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A89', 'C7', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A89', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A90', 'C1', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A90', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A90', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A90', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A90', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A90', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A90', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A90', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A91', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A91', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A91', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A91', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A91', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A91', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A91', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A91', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A92', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A92', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A92', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A92', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A92', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A92', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A92', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A92', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A93', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A93', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A93', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A93', 'C4', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A93', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A93', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A93', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A93', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A94', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A94', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A94', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A94', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A94', 'C5', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A94', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A94', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A94', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A95', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A95', 'C2', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A95', 'C3', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A95', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A95', 'C5', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A95', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A95', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A95', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A96', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A96', 'C2', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A96', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A96', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A96', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A96', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A96', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A96', 'C8', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A97', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A97', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A97', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A97', 'C4', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A97', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A97', 'C6', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A97', 'C7', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A97', 'C8', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A98', 'C1', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A98', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A98', 'C3', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A98', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A98', 'C5', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A98', 'C6', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A98', 'C7', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A98', 'C8', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A99', 'C1', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A99', 'C2', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A99', 'C3', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A99', 'C4', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A99', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A99', 'C6', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A99', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A99', 'C8', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A100', 'C1', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A100', 'C2', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A100', 'C3', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A100', 'C4', 4);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A100', 'C5', 3);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A100', 'C6', 1);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A100', 'C7', 2);
INSERT INTO evaluations (respondent_id, criteria_id, value) VALUES ('A100', 'C8', 2);

